# Labeler configuration for Coherent.js

# Core framework labels
core:
  - changed-files:
      - any-glob-to-any-file: 
          - packages/core/**/*
          - packages/client/**/*
          - packages/runtime/**/*

# API framework labels
api:
  - changed-files:
      - any-glob-to-any-file: 
          - packages/api/**/*

# Integration labels
integrations:
  - changed-files:
      - any-glob-to-any-file: 
          - packages/express/**/*
          - packages/fastify/**/*
          - packages/koa/**/*
          - packages/nextjs/**/*
          - packages/adapters/**/*

# Developer tools labels
devtools:
  - changed-files:
      - any-glob-to-any-file: 
          - packages/devtools/**/*
          - packages/testing/**/*
          - packages/cli/**/*

# Feature packages labels
features:
  - changed-files:
      - any-glob-to-any-file: 
          - packages/i18n/**/*
          - packages/forms/**/*
          - packages/seo/**/*
          - packages/performance/**/*
          - packages/state/**/*

# Backend & Database labels
backend:
  - changed-files:
      - any-glob-to-any-file: 
          - packages/database/**/*

# Build tools labels
build-tools:
  - changed-files:
      - any-glob-to-any-file: 
          - packages/build-tools/**/*
          - packages/profiler/**/*
          - packages/web-components/**/*

# Documentation labels
documentation:
  - changed-files:
      - any-glob-to-any-file: 
          - docs/**/*
          - website/**/*
          - README.md
          - CONTRIBUTING.md
          - CODE_OF_CONDUCT.md
          - SECURITY.md
          - SUPPORT.md
          - "*.md"

# GitHub configuration labels
github-config:
  - changed-files:
      - any-glob-to-any-file: 
          - .github/**/*
          - .junie/**/*

# Test labels
tests:
  - changed-files:
      - any-glob-to-any-file: 
          - packages/*/test/**/*
          - packages/*/src/**/*.{test,spec}.{js,ts}

# Configuration labels
configuration:
  - changed-files:
      - any-glob-to-any-file: 
          - package.json
          - pnpm-lock.yaml
          - eslint.config.js
          - vitest.config.js
          - "*.config.*"
          - "*rc.*"
