name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        # Use current LTS for CI stability; adjust when 22 becomes LTS
        node-version: 20.x
        registry-url: https://registry.npmjs.org/
        # Cache pnpm store between jobs
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8.15.4   # keep in sync with packageManager field in package.json
        
    - name: Install dependencies
      run: pnpm install
      
    - name: Run tests
      run: pnpm test
      
    - name: Publish to npm
      run: pnpm publish --no-git-checks
      if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v') && github.repository == 'Tomdrouv1/coherent.js'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
